name: Jonathan Nuno
layout_spectrum: 0.5170204506789583
typography_spectrum: 0.7463389016103258
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.44708328473547676
  lightness: 0.9331862863948072
  saturation: 0.4655579439700019
  rhythmicContrast: 0.07664312735956053
purpose:
  - type: contact
    label: Contact me
    url: 'mailto:jonathan_nuno@outlook.com'
  - type: external
    label: Check out some of my work!
    url: 'https://github.com/junomars'
title: Programmer. Dungeon Master. Gamer.
description: The devil is in the details.
author:
  name: Jonathan
  email: jonathan_nuno@outlook.com
navigation:
  - name: About Me
    id: 7e10ebe8-6fbe-40ef-95be-a23016c5b1c5
    type: content
content: []
github: true
