typography_spectrum: 0.05084267049096525
color:
  brandStrength: 0.489975661970675
  lightness: 0.4996248628012836
  saturation: 0.25690423999913037
  rhythmicContrast: 0.9898766360711306
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
github: true
layout_spectrum: 0.5735464708413929
author:
  name: Jonathan
  email: jonathan_nuno@outlook.com
name: Jonathan Nuno
title: Programmer. Dungeon Master. Gamer.
content: []
description: The devil is in the details.
purpose:
  - type: contact
    url: 'mailto:jonathan_nuno@outlook.com'
    label: Contact me
  - type: external
    url: 'https://github.com/junomars'
    label: Check out some of my work!
